name: Release

on:
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: "18"
  PNPM_VERSION: "8"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test:run

      - name: Build application
        run: pnpm build

      - name: Generate changelog
        id: changelog
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Generate changelog from git commits
          CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.changelog.outputs.version }}
          body: |
            ## 🚀 Release ${{ steps.changelog.outputs.version }}

            ### Changes
            ${{ steps.changelog.outputs.changelog }}

            ### 📦 Installation
            ```bash
            git clone https://github.com/${{ github.repository }}.git
            cd flagscore
            pnpm install
            pnpm dev
            ```

            ### 🔗 Links
            - **Live Demo:** https://flagscore.fr
            - **Documentation:** https://github.com/${{ github.repository }}/blob/main/README.md

            ### 📊 Performance
            - Lighthouse Score: [View Report](https://github.com/${{ github.repository }}/actions)
            - Bundle Size: Optimized for production
            - Core Web Vitals: ✅ Passing

            ---
            *Automatically generated by GitHub Actions*
          draft: false
          prerelease: false

      - name: Update package.json version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to $VERSION" || exit 0
          git push

  # Déploiement manuel uniquement - pas de déploiement automatique
